tap 'caskroom/cask'
tap 'homebrew/bundle'
tap 'homebrew/php'
tap 'homebrew/science'

brew 'autojump'
brew 'byobu'
brew 'git'
brew 'git-flow'
brew 'git-lfs'
brew 'go'
brew 'direnv'
brew 'dnsmasq'
brew 'editorconfig'
brew 'emacs', args: ['with-cocoa']
brew 'htop-osx'
brew 'markdown'
brew 'mysql'
brew 'nginx'
brew 'node'
brew 'pandoc'
brew 'postgresql'
brew 'ruby-build'
brew 'rbenv'
brew 'ssh-copy-id'
brew 'sqlite'
brew 'the_silver_searcher'
brew 'tig'
brew 'trash'
brew 'zsh'
brew 'zsh-completions'

brew 'homebrew/php/php56'
brew 'homebrew/php/composer'
brew 'homebrew/php/php56-mcrypt'
brew 'homebrew/php/php56-xdebug'
brew 'homebrew/science/r'


cask 'chefdk'